version: "3.9"
services:
  webapi-cqrs-swagger:
    build: .
    ports:
      - "8080:80"
  ms-sql-server:
    image: mcr.microsoft.com/mssql/server:2017-CU22-ubuntu-16.04
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "Pa55w0rd2021"
    ports:
      - "1433:1433"